Document: alt64
Title: Debian alt64 Manual
Author: Tomasz Muras
Abstract: alt64 is a very small
 utility that generates (from a given string) 
 3 possible base64 forms. They in turn can be
 used with a program like grep.
Section: utils

Format: debiandoc-sgml
Files: /usr/share/doc/alt64/alt64.sgml.gz

Format: postscript
Files: /usr/share/doc/alt64/alt64.ps.gz

Format: text
Files: /usr/share/doc/alt64/alt64.text.gz

Format: HTML
Index: /usr/share/doc/alt64/html/index.html
Files: /usr/share/doc/alt64/html/*.html
